// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Family struct {
	ID            *string `json:"id,omitempty"`
	TotalMembers  *int    `json:"totalMembers,omitempty"`
	MaleMembers   *int    `json:"maleMembers,omitempty"`
	FemaleMembers *int    `json:"femaleMembers,omitempty"`
	UserID        *string `json:"userID,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Family *Family `json:"family,omitempty"`
}

type CreateInput struct {
	Name          *string `json:"name,omitempty"`
	TotalMembers  *int    `json:"totalMembers,omitempty"`
	MaleMembers   *int    `json:"maleMembers,omitempty"`
	FemaleMembers *int    `json:"femaleMembers,omitempty"`
}
